- starters/cra-rxjs-styled-components/README.md
> [CRA + RXJS + SC]: Update Readme

- packages/website/src/components/KitActionLinks.astro
- packages/website/src/components/StickyHero.astro
- packages/website/src/layouts/KitLayout.astro
> [Website] Open external links in new tabs

- starters/angular-apollo-tailwind/src/app/app.component.ts
- starters/angular-apollo-tailwind/src/app/counter-example/counter-example.component.html
- starters/angular-apollo-tailwind/src/app/counter-example/counter-example.component.scss
- starters/angular-apollo-tailwind/src/app/fetch-example/fetch-example.component.ts
- starters/angular-apollo-tailwind/src/app/home/home.component.html
- starters/angular-apollo-tailwind/src/app/home/home.component.scss
Resolves #197 
> # Background
> All the scaffolded SCSS files have no classes or content. We should do one of the following:
> 1. Find repeat component styles and lift them into the SCSS files using Tailwind's `@apply`
> 2. Delete the files as unused.
> 
> # Acceptance
> - Abstract the counter button styles to the SCSS file for reuse
> - Delete the fetch component SCSS file
> - Delete the app SCSS file
> [angular-apollo-tailwind] Remove empty SCSS files #197

- starters/angular-apollo-tailwind/src/app/counter-example/counter-example.component.html
- starters/angular-apollo-tailwind/src/app/counter-example/counter-example.component.scss
- starters/angular-apollo-tailwind/src/app/fetch-example/fetch-example.component.html
- starters/angular-apollo-tailwind/src/app/home/home.component.html
- starters/angular-apollo-tailwind/src/app/home/home.component.scss
- starters/angular-apollo-tailwind/src/index.html
> #204 [angular-apollo-tailwind] Update kit styles to match other kits

- starters/angular-ngrx-scss/src/app/counter-example/counter-example.component.html
- starters/angular-ngrx-scss/src/app/counter-example/counter-example.component.scss
- starters/angular-ngrx-scss/src/app/counter-example/starter-button/starter-button.scss
- starters/angular-ngrx-scss/src/app/fetch-example/fetch-example.component.scss
- starters/angular-ngrx-scss/src/app/home/home.component.html
- starters/angular-ngrx-scss/src/app/home/home.component.scss
- starters/angular-ngrx-scss/src/styles.scss
> [Angular-NgRx-SCSS] Make Styles Consistent with Other Starters

- starters/angular-ngrx-scss/src/app/app.module.ts
- starters/angular-ngrx-scss/src/app/fetch-example/fetch-example.component.html
- starters/angular-ngrx-scss/src/app/fetch-example/fetch-example.component.scss
- starters/angular-ngrx-scss/src/app/fetch-example/loader/loader.component.html
- starters/angular-ngrx-scss/src/app/fetch-example/loader/loader.component.scss
- starters/angular-ngrx-scss/src/app/fetch-example/loader/loader.component.ts
> [angular-ngrx-scss] - Update loader styles on fetch example

- starters/vue3-apollo-quasar/tests/unit/FetchExample.spec.ts
- starters/vue3-apollo-quasar/tsconfig.json
closes #280 
Test re-written complete
> test: test re-written

- starters/vue3-apollo-quasar/tests/unit/NumberCounter.spec.ts
- starters/vue3-apollo-quasar/tsconfig.json
closes #281 
Test re-written completed.
> test: re-written completed

- starter-kits.json
- starters/vue3-apollo-quasar/package.json
> fix: create vue kit

- packages/create-starter/README.md
- packages/create-starter/package.json
- packages/create-starter/src/index.ts
- packages/create-starter/src/utils.ts
- starters/angular-apollo-tailwind/README.md
- starters/angular-ngrx-scss/README.md
- starters/cra-rxjs-styled-components/README.md
- starters/next-react-query-tailwind/README.md
- starters/remix-gql-tailwind/README.md
- starters/vue3-apollo-quasar/README.md
- yarn.lock
- Add support for CLI args
- Updated CLI README
- Updates existing kit readmes to use the --kit arg
User can now generate starter kits providing --name and --kit params. If a parameter is not used it will start in interactive mode as normal to prompt for any missing args
Closes #25
> feat(cli): CLI arg support

- starters/svelte-kit-scss/.editorconfig
- starters/svelte-kit-scss/src/app.html
- starters/svelte-kit-scss/src/routes/sverdle/+page.server.ts
- starters/svelte-kit-scss/src/routes/sverdle/+page.svelte
Resolves: #386 
Having code style consistency is important for any project. A standardized set of options should be set that can be overwritten by the implementer at a later date.
This task has already been completed many times on different KITs, so we should make sure to look at those configurations first and try not to reinvent the wheel :)
> [sveltekit-pod] 1. Add linting and prettier configurations

- starters/solidjs-tanstack-tailwind/.editorconfig
- starters/solidjs-tanstack-tailwind/.eslintignore
- starters/solidjs-tanstack-tailwind/.eslintrc.json
- starters/solidjs-tanstack-tailwind/.prettierignore
- starters/solidjs-tanstack-tailwind/.prettierrc
- starters/solidjs-tanstack-tailwind/package.json
Having code style consistency is important for any project. A standardized set of options should be set that can be overwritten by the implementer at a later date.
This task has already been completed many times on different KITs, so we should make sure to look at those configurations first and try not to reinvent the wheel :)
> SolidJS Linting prettier

- starters/qwik-fetch-tailwind/.eslintrc.cjs
- starters/qwik-fetch-tailwind/.prettierrc
- starters/qwik-fetch-tailwind/package.json
- starters/qwik-fetch-tailwind/src/components/router-head/router-head.tsx
> (feat): Add linting prettier to qwik pod #348

- starters/qwik-fetch-tailwind/.eslintrc.cjs
- starters/qwik-fetch-tailwind/.npmrc
- starters/qwik-fetch-tailwind/.storybook/main.ts
- starters/qwik-fetch-tailwind/.storybook/preview-head.html
- starters/qwik-fetch-tailwind/.storybook/preview.ts
- starters/qwik-fetch-tailwind/package.json
- starters/qwik-fetch-tailwind/src/routes/counter/counter.stories.tsx
- starters/qwik-fetch-tailwind/src/routes/counter/counter.tsx
- starters/qwik-fetch-tailwind/src/routes/counter/index.tsx
- starters/qwik-fetch-tailwind/src/routes/data-fetching/data-fetching.stories.tsx
- starters/qwik-fetch-tailwind/src/routes/data-fetching/data-fetching.tsx
- starters/qwik-fetch-tailwind/src/routes/data-fetching/index.tsx
Closes #344 
> To be merged after [391](https://github.com/thisdot/starter.dev/pull/391)
> Qwik fetch tailwind/344 setup storybook

- starters/solidjs-tanstack-tailwind/LICENSE
- starters/solidjs-tanstack-tailwind/package.json
Very small PR to keep the permissions right.
> SolidJS set correct license and privacy

- starters/qwik-graphql-tailwind/README.md
- starters/qwik-graphql-tailwind/package.json
> feat: Update readme for Qwik starter

- starters/svelte-kit-scss/README.md
Resolves: #383
> # Background
> The kit should include a thorough README with all architectural decisions the user should be aware of when utilizing it. It shouldn't rewrite docs for existing libraries but any key decisions should be documented. This is what will be visible to users on the website when they look at the details page.
> 
> # Acceptance
> - [x] Update the below template with relevant information for users who want to utilize this kit with appropriate instructions.
> 
> # Template
> 
> > # <kit name> starter kit
> > 
> > This starter kit features <technology list>.
> > 
> > ## Table of Contents
> > 
> > - [Overview](#overview)
> >   - [Tech Stack](#tech-stack)
> >   - [Included Tooling](#included-tooling)
> >   - [Example Components](#example-components)
> > - …
> [sveltekit-pod] 3. Update the readme

- starters/qwik-graphql-tailwind/package.json
- starters/qwik-graphql-tailwind/src/routes/counter/counter.test.tsx
- starters/qwik-graphql-tailwind/src/routes/data-fetching/data-fetching.test.tsx
- starters/qwik-graphql-tailwind/tsconfig.json
- starters/qwik-graphql-tailwind/vite.config.ts
Closes #353 
- Added vitest configuration with example tests for the counter and data fetching components.
> [qwik-pod] feat: Added vitest configuration with example tests

- packages/website/src/config.tsx
- packages/website/src/icons/SolidJsIcon.tsx
- packages/website/src/icons/index.ts
The website has attempted to include all the kits appropriately but may need some added configuration to display correctly.
> chore: added kit to main site and added solidjs icon

- starters/solidjs-tailwind/README.md
> docs(solidjs): implement readme template

- packages/website/src/components/KitItem.astro
- packages/website/src/config.tsx
- starter-kits.json
- starters/svelte-kit-scss/package.json
resolves #384
> # Background
> The website has attempted to include all the kits appropriately but may need some added configuration to display correctly.
> 
> # Acceptance
> - [x] Ensure the kit displays on the website
> - [x] Add any missing logos for technologies as needed
Result: (UPDATED)
> feat: [sveltekit-pod] 4. Add Kit on the main site

- starters/solidjs-tailwind/README.md
Repository link in the readme is wrong, and also there is a styling issue with H5 in the readme.
> chore: modified README

- packages/website/src/components/Footer.astro
This PR adds the website link in the footer.
closes #470
> chore: adding this dot link for footer

- starters/svelte-kit-scss/package.json
Fix issue referenced here: https://thisdot-labs.slack.com/archives/C0475BB41DW/p1666758616346219
This may apply to both showcase and kit
> [sveltekit-pod] Fix issues with storybook and npm

- .github/pull_request_template.md
I have created a basic PR template to help new and returning contributors provide all of the necessary information on changes made. 
closes #521
> docs: creating starter.dev PR template

- starters/graphql-serverless-contentful/serverless.yml
- starters/graphql-serverless-contentful/src/handlers/healthcheck.test.ts
- starters/graphql-serverless-contentful/src/handlers/healthcheck.ts
> feat: adds healthcheck

- starters/svelte-kit-scss/README.md
- starters/svelte-kit-scss/package.json
> chore: add-showcase-to-sveltekit

- starters/express-typescript-typeorm-postgres/src/bootstrap-app.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/create-technology.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/delete-technology.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/get-all-technology.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/get-technology.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/update-technology.ts
Added error handling to existing endpoints.
> [NODE] feat: added error handlers

- starters/graphql-serverless-contentful/README.md
> [graphql-pod-kit1] Create README For Graphql-Serverless Kit

- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/create-technology.spec.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/delete-technology.spec.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/get-all-technology.spec.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/get-all-technology.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/get-technology.spec.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/update-technology.spec.ts
- starters/express-typescript-typeorm-postgres/src/main.spec.ts
Added unit tests to the starter kit default CRUD handlers
> [NODE] Feat/580 unit tests

- starters/deno-oak-denodb/README.md
- starters/deno-oak-denodb/deno.json
- starters/deno-oak-denodb/src/main.ts
> [Deno] Add liniting and prettier configuration

- starters/express-typescript-typeorm-postgres/src/bootstrap-app.ts
- starters/express-typescript-typeorm-postgres/src/controllers/router.ts
According to the latest specification, the health check endpoint should be at `/health`
> [NODE] Fix/581 move health endpoint

- packages/website/src/components/Footer.astro
Adds a "Deploys by Netlify" badge to the site's footer.
> feat(website): adds netlify badge

- packages/website/src/config.tsx
- Change the label for SolidJs to SolidJS.
Closes: #601
> feat(SolidJS): Fix misspelled label

- starters/remix-gql-tailwind/README.md
> fix(remix-gql-tailwind): README typo fix

- starters/next12-routing-chakra-ui/__tests__/counter-example.test.tsx
- starters/next12-routing-chakra-ui/__tests__/fetch-example.test.tsx
- starters/next12-routing-chakra-ui/__tests__/index.test.tsx
- starters/next12-routing-chakra-ui/jest.config.js
- starters/next12-routing-chakra-ui/package.json
- starters/next12-routing-chakra-ui/src/pages/counter-example/index.tsx
- starters/next12-routing-chakra-ui/src/pages/fetch-example/[[...slug]].tsx
- starters/next12-routing-chakra-ui/src/pages/index.tsx
This PR adds Jest testing to the Next12 and Chakra UI starter kit.
> [Next12-ChakraUI kit] adding jest testing

- starters/express-typescript-typeorm-postgres/.env.example
- starters/express-typescript-typeorm-postgres/.gitignore
- starters/express-typescript-typeorm-postgres/README.md
- starters/express-typescript-typeorm-postgres/docker-compose.yml
- starters/express-typescript-typeorm-postgres/package.json
- starters/express-typescript-typeorm-postgres/src/bootstrap-app.ts
- starters/express-typescript-typeorm-postgres/src/controllers/health/handlers/get-health.ts
- starters/express-typescript-typeorm-postgres/src/controllers/health/services/health.service.ts
- starters/express-typescript-typeorm-postgres/src/controllers/queue/queue.controller.ts
- starters/express-typescript-typeorm-postgres/src/controllers/router.ts
- starters/express-typescript-typeorm-postgres/src/controllers/technology/handlers/create-technology.ts
- starters/express-typescript-typeorm-postgres/src/queue/config.constants.ts
- starters/express-typescript-typeorm-postgres/src/queue/job-processor.ts
- starters/express-typescript-typeorm-postgres/src/queue/queue.ts
- Added another redis instance
- set up bullMQ connection
- set up basic queue controller
- set up worker to run on different thread
> [NODE] feat: initial setup of bullMQ

- starters/deno-oak-denodb/.editorconfig
Closes #623.
This adds the `.editorconfig` file.
> [deno] Add editorconfig

- starters/expo-zustand-styled-component/package.json
- starters/expo-zustand-styled-component/src/screens/Home/Home.styles.ts
- starters/expo-zustand-styled-component/src/screens/Home/Home.tsx
> EZSC - Web header bug

- starters/qwik-graphql-tailwind/package.json
Closes: https://github.com/thisdot/starter.dev/issues/626
Updated some deps due to new releases that fixed some certain bugs we faced during the showcase.
> updated qwik qwik-city storybook and vite to latest versions

- starters/deno-oak-denodb/Dockerfile
> [Deno] Containerization and Deployment

- starters/next12-routing-chakra-ui/.eslintrc.json
- starters/next12-routing-chakra-ui/.storybook/main.js
- starters/next12-routing-chakra-ui/.storybook/preview.js
- starters/next12-routing-chakra-ui/README.md
- starters/next12-routing-chakra-ui/src/components/greeting/index.tsx
- starters/next12-routing-chakra-ui/src/pages/api/hello.ts
This PR updates the README and fixes some formatting issues that were resolved by Prettier.
> [next12-chakra ui] updating README and fixing formatting

- starters/deno-oak-denodb/src/graphql/interfaces/codegen.ts
- starters/deno-oak-denodb/src/graphql/resolvers/query_handler.ts
- starters/deno-oak-denodb/src/graphql/resolvers/resolvers.ts
- starters/deno-oak-denodb/src/graphql/schema/technology.ts
- starters/deno-oak-denodb/src/rest/services/healtcheck_service.ts
> [Deno] fix graphql review comment

- starters/deno-oak-denodb/README.md
> [Deno] add info about database setup

- starters/svelte-kit-scss/src/routes/(examples)/api-example/+page.server.ts
> fix: greeting link

- starters/qwik-graphql-tailwind/src/components/button/button.classNames.ts
- starters/qwik-graphql-tailwind/src/routes/counter/counter.classNames.ts
- starters/qwik-graphql-tailwind/src/routes/counter/counter.tsx
> feat(qwik-pod): Fix styles counter component

- starters/qwik-graphql-tailwind/src/routes/counter/index.tsx
- starters/qwik-graphql-tailwind/src/routes/data-fetching/index.tsx
- starters/qwik-graphql-tailwind/src/routes/index.tsx
- starters/qwik-graphql-tailwind/src/utils/constants.ts
Updated head titles to show:
- "qwik-graphql-tailwind starter.dev" on homepage
- "Counter | qwik-graphql-tailwind starter.dev" on the counter example page
- "Data Fetching | qwik-graphql-tailwind starter.dev" on the data fetching example page
> fix (qwik-pod): update head titles

- starters/qwik-graphql-tailwind/README.md
Added information on all available scripts to README.md.
> chore (qwik-pod): add description of all scripts to readme

- starters/svelte-kit-scss/.eslintignore
- starters/svelte-kit-scss/src/routes/(examples)/api-example/+page.server.ts
> [svelte-kit-scss] P1: Fix Linting Errors

- starters/deno-oak-denodb/README.md
Minor fixes in the Deno readme.
> Fix overflow and wrong installation instruction

- starters/qwik-graphql-tailwind/src/root.tsx
> Qwik replace deprecations

- starters/deno-oak-denodb/README.md
> Add back CLI instructions for Deno

- starters/qwik-graphql-tailwind/src/routes/counter/counter.test.tsx
- starters/qwik-graphql-tailwind/src/routes/data-fetching/data-fetching.test.tsx
- Counter test fixed and improved
- data-fetching test fixed
Fixes: #662
Fixes: #672 
Fixes: #673 
Fixes: #674 
Fixes: #671
> fix(qwik-pod): counter and data fetching tests

- starters/qwik-graphql-tailwind/src/components/button/button.classNames.ts
- starters/qwik-graphql-tailwind/src/components/button/button.tsx
- starters/qwik-graphql-tailwind/src/routes/homepage.classNames.ts
- starters/qwik-graphql-tailwind/src/routes/index.tsx
- starters/qwik-graphql-tailwind/src/routes/layout.classNames.ts
- starters/qwik-graphql-tailwind/src/routes/layout.tsx
Moved all tailwind classes from separate files to components' JSX files
Fixes: #670
> fix(qwik-pod): moved tailwind classes into JSX files

- .vscode/settings.json
- packages/website/.gitignore
- packages/website/astro.config.mjs
- packages/website/package.json
- packages/website/scripts/generate-kit-pages.js
- packages/website/src/components/KitNavigation.tsx
- packages/website/src/components/MobileNavigation.tsx
- packages/website/src/components/TableOfContents.tsx
- packages/website/src/components/TechStacksSection.astro
- packages/website/src/layouts/BaseLayout.astro
- packages/website/src/layouts/KitLayout.astro
- packages/website/src/pages/404.astro
- packages/website/src/pages/kits-by-tool/[key].astro
- packages/website/src/pages/kits-by-tool/index.astro
- yarn.lock
- Upgrades to latest version of Astro (v1) from Astro v1-beta
https://docs.astro.build/en/migrate/#astro-10
Closes https://github.com/thisdot/pods/issues/125
> chore(website): Astro Upgrade

- packages/website/src/layouts/BaseHead.astro
> added astro dicrective to fix dark mode flisker

- starters/solidjs-tailwind/src/components/FetchExample/greetingFetcher.js
Issues with the data fetching component were resolved by updating the API for solidjs,
> update greeting api endpoint

- starters/solidjs-tailwind/src/components/CounterExample/Counter.spec.jsx
- starters/solidjs-tailwind/src/components/CounterExample/counterStore.js
- currently, the decrement button does not allow numbers to go past zero into negative numbers. The app should allow going into the negative
> decrement shows negative values and also a test to do same implemented

- starters/solidjs-tailwind/src/components/FetchExample/Greeting.stories.jsx
- starters/solidjs-tailwind/src/components/FetchExample/greetingFetcher.js
Updated the API on the storybook
> Soildjs greeting api update

- starters/qwik-graphql-tailwind/package.json
- starters/qwik-graphql-tailwind/src/components/data-fetching/data-fetching.tsx
Issues with the data fetching component were resolved by updating the API for solidjs, while the Qwik starter was refactored to use query params.
> Greeting api update

- starters/qwik-graphql-tailwind/src/routes/counter-example/index.tsx
- starters/qwik-graphql-tailwind/src/routes/data-fetching/index.tsx
- starters/qwik-graphql-tailwind/src/routes/index.tsx
- starters/qwik-graphql-tailwind/src/routes/layout.tsx
> Removed white space

- starters/qwik-graphql-tailwind/README.md
- starters/qwik-graphql-tailwind/src/routes/counter-example/index.tsx
Added return home link to counter page
Updated the readme doc
> update readme and added return home link

- starters/solidjs-tailwind/README.md
> feat(solidjs-pod): Reorder readme sections

- starters/qwik-graphql-tailwind/src/components/button/button.tsx
- starters/qwik-graphql-tailwind/src/components/counter/counter.tsx
- starters/qwik-graphql-tailwind/src/components/data-fetching/data-fetching.classNames.ts
- starters/qwik-graphql-tailwind/src/components/data-fetching/data-fetching.tsx
- starters/qwik-graphql-tailwind/src/routes/counter-example/index.tsx
- starters/qwik-graphql-tailwind/src/routes/data-fetching/index.tsx
- starters/qwik-graphql-tailwind/src/routes/index.tsx
- starters/qwik-graphql-tailwind/src/routes/layout.tsx
Added input field to allow user entry for custom name
> Added Input field for user name entry

- starters/qwik-graphql-tailwind/package.json
- starters/qwik-graphql-tailwind/src/components/button/button.tsx
- starters/qwik-graphql-tailwind/src/components/button/index.ts
- starters/qwik-graphql-tailwind/src/components/counter/counter.tsx
- starters/qwik-graphql-tailwind/src/components/data-fetching/data-fetching.tsx
- starters/qwik-graphql-tailwind/src/components/data-fetching/index.ts
- starters/qwik-graphql-tailwind/src/routes/counter-example/index.tsx
- starters/qwik-graphql-tailwind/src/routes/data-fetching/index.tsx
- starters/qwik-graphql-tailwind/src/routes/index.tsx
- starters/qwik-graphql-tailwind/src/routes/layout.tsx
- starters/qwik-graphql-tailwind/tsconfig.json
- Used absolute paths https://github.com/thisdot/starter.dev/issues/749
- Removed double file name imports https://github.com/thisdot/starter.dev/issues/750
- Installed the prettier tailwind plugin to order the tailwind classnames
> [qwik-graphql-tailwind] clean up the starter kit

- starters/qwik-graphql-tailwind/src/components/data-fetching/data-fetching.tsx
Change the placeholder in data fetching button.
Fixes: #756
> fix: change placeholder in data fetching component

- starters/solidjs-tailwind/.eslintrc.json
> feat(solidjs-pod): Add missing eslint config

- starter-kits.json
- starters/solidjs-tailwind/README.md
- starters/solidjs-tailwind/package.json
- starters/solidjs-tailwind/src/pages/Home.jsx
> feat(solidjs-pod): SolidJS naming change

- starters/solidjs-tailwind/package.json
- starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
- starters/solidjs-tailwind/src/mock/greetingHandler.js
- starters/solidjs-tailwind/src/mock/serverSetup.js
- P1: fix failing test (Greeting.spec.jsx)
- Fixed
> [solidjs-tailwind] P1: fix failing test

- .github/dependabot.yml
Adds dependabot.yml for auto PRs for website and cli
> feat: adds dependabot config for auto PRs for website and cli

- starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
- starters/solidjs-tailwind/src/components/FetchExample/greetingFetcher.js
Added input to receive a user-customized name for display and refactor the greeting component
> [solidjs-pod] - Greeting Input field 

- starters/solidjs-tailwind/README.md
> [solidjs-tailwind] Spell check the README

- starters/qwik-graphql-tailwind/.storybook/main.ts
Now storybook should work
Fixes: #786
> fix: storybook

- starters/qwik-graphql-tailwind/src/components/counter/counter.test.tsx
- starters/qwik-graphql-tailwind/src/components/data-fetching/data-fetching.test.tsx
- starters/qwik-graphql-tailwind/src/utils/useStarterQuery.ts
Fix tests that fail. Fix `yarn lint` errors. Now `yarn build` command works.
Fixes: #781 
Fixes: #782 
Fixes: #783
> fix: tests, linting errors and build fail

- starters/graphql-serverless-contentful/package.json
> fix: missing@graphql-tools/merge

- starters/graphql-serverless-contentful/README.md
> [serverless-apollo-contentful] pnpm is not mentioned and needs to be verified

- starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
- All test should pass. Greeting.spec.jsx is currently failing
> solidjs all test pass

- starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
Fix linting warning and files.
Fixes: #815
Fixes: #814
> solidjs-fix: linting warning

- starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
- starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
> feat(solidjs-pod): Fix starter kit greeting component

- starters/solidjs-tailwind/src/components/FetchExample/Greeting.stories.jsx
- errors when running Storybook on the starter kit (see image below)
> error fixed

- starters/solidjs-tailwind/.eslintrc.json
- starters/solidjs-tailwind/.husky/pre-commit
- starters/solidjs-tailwind/package.json
- starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
- starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
- starters/solidjs-tailwind/src/mock/greetingHandler.js
- starters/solidjs-tailwind/src/mock/serverSetup.js
Formatted all files and add husky pre-commit hook in order to always format files before a commit.
Fixes: #852
> Solid fix: format code and add pre commit hook

- starters/solidjs-tailwind/README.md
> Add project to docs site

- starters/solidjs-tailwind/package.json
> feat(solidjs-pod): fix lint-fix command

- starters/solidjs-tailwind/README.md
Fix readme file.
Fixes: #884 
Fixes: #883 
Fixes: #882 
Fixes: #881
> solidjs-fix: readme

- starters/solidstart-tanstackquery-tailwind-modules/package.json
- starters/solidstart-tanstackquery-tailwind-modules/src/components/CounterExample/Counter.spec.tsx
> fix counter test

- starters/solidjs-tailwind/README.md
- starters/solidstart-tanstackquery-tailwind-modules/README.md
> Solidstart tanstack tailwind readme update

- starters/solidstart-tanstackquery-tailwind-modules/.husky/pre-commit
- starters/solidstart-tanstackquery-tailwind-modules/package.json
- starters/solidstart-tanstackquery-tailwind-modules/src/components/FetchExample/Greeting.tsx
Add yarn format and yarn lint in pre-commit hook
Fixes: #933
> Solidstart feature: add precommit hook

- starters/solidstart-tanstackquery-tailwind-modules/README.md
> Fix typos in README

- starters/solidstart-tanstackquery-tailwind-modules/README.md
> updated the script commands

- starters/solidstart-tanstackquery-tailwind-modules/README.md
> Command Rearrangement

- starters/solidstart-tanstackquery-tailwind-modules/package.json
- starters/solidstart-tanstackquery-tailwind-modules/src/root.tsx
- starters/solidstart-tanstackquery-tailwind-modules/src/routes/index.tsx
- "SolidStart - TanStackQuery - TailwindCss - Css Modules - Kit" should be changed to "Solid Start - Tanstack Query - Tailwind CSS - CSS Modules Kit"
> title corrections

- starters/express-apollo-prisma/docker-compose.yaml
- starters/express-apollo-prisma/package.json
> [express-apollo-prisma] Clean up docker commands 

- starters/express-apollo-prisma/README.md
> [express-apollo-prisma] Add README.md

- starters/graphql-serverless-contentful/README.md
- starters/graphql-serverless-contentful/package.json
> [serverless-apollo-contentful] Clean up README.md

- starters/solidjs-tailwind/README.md
> Soildjs readme update

- starters/solidstart-tanstackquery-tailwind-modules/README.md
Removed demo implementation link from readme
Fixes: #975
> solidstart-fix: remove demo implementation link from readme

- starters/graphql-serverless-contentful/package.json
- starters/graphql-serverless-contentful/src/utils/sqs/sendMessage.test.ts
- starters/graphql-serverless-contentful/src/utils/sqs/sendMessage.ts
> [serverless-apollo-contentful] Unit test for utils/sqs/sendMessage.ts

- starters/solidstart-tanstackquery-tailwind-modules/README.md
> solidstart-fix: readme file

- starters/next12-react-query-tailwind/package.json
Upgrades dependencies to latest minor versions 
Closes #999
> chore(next12-react-query-tailwind): Minor version dep upgrades

- starter-kits.json
> [express-apollo-prisma] Add the kit to starter.dev CLI

- starters/serverless-apollo-contentful/README.md
> [serverless-apollo-contentful] Queueing feature documentation

- starters/serverless-apollo-contentful/src/handlers/sqs-generate-job.spec.ts
> [serverless-apollo-contentful] Add Unit tests: src\handlers\sqs-generate-job.ts

- starters/solidstart-tanstackquery-tailwind-modules/package.json
Added missing package in package.json 
Fixes: #1061
> solidstart-fix: added missing library

- starter-kits.json
> [Expo] Add Expo starter to CLI command list

- starters/express-apollo-prisma/prisma/seed.ts
> [express-apollo-prisma] Add Seeding Migration

- starters/express-apollo-prisma/prisma/schema.prisma
- starters/express-apollo-prisma/src/healthcheck/datasource-healthcheck.spec.ts
- starters/express-apollo-prisma/src/healthcheck/datasource-healthcheck.ts
- starters/express-apollo-prisma/src/healthcheck/healthcheck-handler.spec.ts
- starters/express-apollo-prisma/src/healthcheck/healthcheck-handler.ts
- starters/express-apollo-prisma/src/healthcheck/redis-healthcheck.spec.ts
- starters/express-apollo-prisma/src/healthcheck/redis-healthcheck.ts
- starters/express-apollo-prisma/src/mocks/express.ts
> [express-apollo-prisma] Unit testing: healthcheck/healthcheck-handler.ts

- starters/express-apollo-prisma/src/cache/redis/connect-redis-client.spec.ts
- starters/express-apollo-prisma/src/cache/redis/connect-redis-client.ts
> [express-apollo-prisma] Unit testing (logic, excluding client event handlers): cache/redis/connect-redis-client

- starters/express-apollo-prisma/src/graphql/graphql-server.spec.ts
- starters/express-apollo-prisma/src/mocks/graphql-server.ts
> [express-apollo-prisma] Unit Tests: src/graphql/graphql-server.ts

- starters/serverless-apollo-contentful/src/utils/redis/redis.spec.ts
> 1111-redis-spec-fix-warning

- starters/express-apollo-prisma/src/mocks/queue.ts
- starters/express-apollo-prisma/src/queue/job-generator-handler.spec.ts
- starters/express-apollo-prisma/src/queue/job-generator-handler.ts
Closes #1099 
Add tests for generator endpoint
> [express-apollo-prisma] Unit tests for Queueing

- starters/serverless-apollo-contentful/README.md
> fix: readme grammar corrections

- starters/solidjs-tailwind/.husky/pre-commit
- starters/solidjs-tailwind/package.json
Remove husky and pinned all right packages versions in package manager
Fixes: #1118
> solidjs-fix: remove husky

- starters/express-apollo-prisma/README.md
> [express-apollo-prisma] Add queueing documentation to README

- starters/express-apollo-prisma/src/cache/index.ts
Make CacheAPIWrapper d.ts compatible with pnpm
> [express-apollo-prisma] Final review and deployment

- starters/express-apollo-prisma/README.md
- starters/express-apollo-prisma/package.json
Added Prisma Studio to package.json & Readme
> [express-apollo-prisma] Update README to detail the Prisma studio

- starters/express-apollo-prisma/README.md
> [exress-apollo-prisma] Update-deployment-readme

- starters/solidstart-tanstackquery-tailwind-modules/README.md
- starters/solidstart-tanstackquery-tailwind-modules/package.json
- starters/solidstart-tanstackquery-tailwind-modules/src/root.tsx
- starters/solidstart-tanstackquery-tailwind-modules/src/routes/api-example.tsx
- starters/solidstart-tanstackquery-tailwind-modules/src/routes/index.tsx
Clean up Solid Start kit
Fixes: #1126
> solidstart-fix: clean up code

- starters/serverless-framework-apollo-contentful/README.md
> chore: update readme to fix image addresses

- starters/serverless-framework-apollo-contentful/.prettierignore
- starters/serverless-framework-apollo-contentful/README.md
- starters/serverless-framework-apollo-contentful/package.json
- starters/serverless-framework-apollo-contentful/src/schema/technology/technology.resolver.spec.ts
- starters/serverless-framework-apollo-contentful/src/utils/test/mocks/contentful/entry.ts
1. Add how to implement queue
2. Grammar errors in readme
3. Run prettier format
4. Add .prettierignore file
> [serverless-framework-apollo-contentful] Cleanup

- packages/website/src/icons/HeroRectangleBg.tsx
Remove invalid `viewBox` attribute in HeroRectangleBg
> fix: 940 remove problematic viewBox in HeroRectangleBg

- starters/vue3-xstate-css/.gitignore
- starters/vue3-xstate-css/cypress.config.ts
- starters/vue3-xstate-css/cypress/e2e/example.cy.ts
- starters/vue3-xstate-css/cypress/fixtures/example.json
- starters/vue3-xstate-css/package.json
- starters/vue3-xstate-css/src/assets/base.css
- starters/vue3-xstate-css/src/machines/counterMachine.ts
- starters/vue3-xstate-css/src/machines/greetMachine.ts
- starters/vue3-xstate-css/src/router/index.ts
- starters/vue3-xstate-css/src/stories/GreetView.stories.js
- starters/vue3-xstate-css/src/views/CounterView.vue
- starters/vue3-xstate-css/src/views/GreetView.vue
- starters/vue3-xstate-css/src/views/__tests__/GreetView.cy.ts
- starters/vue3-xstate-css/tsconfig.app.json
- starters/vue3-xstate-css/tsconfig.cypress-ct.json
Minor cleanup of
- unnecessary comments
- leftover example code that's not used
- minor refactors for consistency
> [Vue3-XState] Cleanup kit tasks

- starters/next13-zustand-bulma/jest.config.js
- starters/next13-zustand-bulma/jest.setup.js
- starters/next13-zustand-bulma/package.json
- Adds jest with Next.js built-in Jest configuration
- Adds testing-library packages for react component testing support
- Adds working initial demo test
- Adds "test" script to package.json
Closes #992
> feat(next13-zustand-bulma): Adds Jest component testing support

- starters/serverless-framework-apollo-contentful/.env.example
- starters/serverless-framework-apollo-contentful/README.md
- starters/serverless-framework-apollo-contentful/src/handlers/graphql.ts
- starters/serverless-framework-apollo-contentful/src/handlers/sqs-generate-job.ts
> [serverless-framework-apollo-contentful] quality of life fixes

- starters/next13-zustand-bulma/README.md
- starters/next13-zustand-bulma/src/app/api-example/page.module.scss
- starters/next13-zustand-bulma/src/app/api-example/page.tsx
- starters/next13-zustand-bulma/src/components/Greeting/Greeting.tsx
- starters/next13-zustand-bulma/src/components/Greeting/index.ts
- Added a new component for the fetch api example
- Updated README.md file
https://user-images.githubusercontent.com/39612839/227647260-c80d8cc5-7e6d-4b08-8042-d2def657fec2.mp4
> Feat(next13-zustand-bulma): Add fetch example

- .github/ISSUE_TEMPLATE/security_report.yml
- CODE_OF_CONDUCT.md
- LICENCE
- SECURITY.md
Updating repo policies and documents to better align with community expectations.
> Update policy docs

- starters/lit-mobx-vaadin/.prettierrc
- starters/lit-mobx-vaadin/index.html
- starters/lit-mobx-vaadin/package.json
- starters/lit-mobx-vaadin/src/components/Counter/Counter.ts
- starters/lit-mobx-vaadin/src/components/vaadin-button/vaadin-button-styles.ts
- starters/lit-mobx-vaadin/src/components/vaadin-button/vaadin-button.ts
- starters/lit-mobx-vaadin/src/components/vaadin-horizontal-layout/vaadin-horizontal-layout-styles.ts
- starters/lit-mobx-vaadin/src/components/vaadin-horizontal-layout/vaadin-horizontal-layout.ts
- starters/lit-mobx-vaadin/src/components/vaadin-vertical-layout/vaadin-vertical-layout-styles.ts
- starters/lit-mobx-vaadin/src/components/vaadin-vertical-layout/vaadin-vertical-layout.ts
- starters/lit-mobx-vaadin/src/pages/counter-example/starter-counter.ts
- starters/lit-mobx-vaadin/src/pages/home/starter-home.ts
- starters/lit-mobx-vaadin/src/pages/page.mixin.ts
- starters/lit-mobx-vaadin/src/pages/starter-app.ts
- starters/lit-mobx-vaadin/src/pages/starter-layout.ts
- starters/lit-mobx-vaadin/src/router.ts
- starters/lit-mobx-vaadin/src/state.ts
Resolves #1222 (partiallly, no tests/storybook yet, until setup is ready)
Resolves #1221
> [Lit -Mobx -Vaadin] add counter page and component

- starters/nuxt3-pinia-vuetify/app.vue
- starters/nuxt3-pinia-vuetify/components/CounterExample/CounterExample.vue
- starters/nuxt3-pinia-vuetify/components/FetchExample/FetchExample.vue
- starters/nuxt3-pinia-vuetify/nuxt.config.ts
- starters/nuxt3-pinia-vuetify/pages/index.vue
- starters/nuxt3-pinia-vuetify/store/counterStore.ts
Added changes to the kit improving styles (in order to match other kits), files structures and auto-import feature with Pinia
> [Nuxt 3 - Pinia - Vuetify] Fix: sanity check

- starters/lit-mobx-vaadin/.eslintrc
- starters/lit-mobx-vaadin/.gitignore
- starters/lit-mobx-vaadin/.prettierrc
- starters/lit-mobx-vaadin/package.json
- starters/lit-mobx-vaadin/playwright.config.ts
- starters/lit-mobx-vaadin/tests/pages/counter-example/starter-counter.spec.ts
- starters/lit-mobx-vaadin/tests/pages/home/starter-home.spec.ts
- starters/lit-mobx-vaadin/web-dev-server.config.mjs
Adds Playwright to the project and also tests for already existing pages.
> [Lit-Mobx-Vaadin] Add Playwright

- packages/metrics-handler/index.js
Just ran prettier on `packages/metrics-handler/index.js`
The real objective of this commit is to trigger the gh action, possibly fixed in PR https://github.com/thisdot/starter.dev/pull/1238
> chore: run prettier on index.js

- packages/metrics-handler/README.md
Trigger GH action.
Just ran prettier on readme file.
> chore: run prettier on readme file

- starters/lit-mobx-vaadin/.eslintrc
- starters/lit-mobx-vaadin/index.html
- starters/lit-mobx-vaadin/index.storybook.html
- starters/lit-mobx-vaadin/src/api/fetch.ts
- starters/lit-mobx-vaadin/src/components/fetch/fetch.ts
- starters/lit-mobx-vaadin/src/pages/counter-example/starter-counter.ts
- starters/lit-mobx-vaadin/src/pages/fetch-example/starter-fetch.ts
- starters/lit-mobx-vaadin/src/pages/home/starter-home.ts
- starters/lit-mobx-vaadin/src/pages/page.mixin.ts
- starters/lit-mobx-vaadin/src/pages/starter-app.ts
- starters/lit-mobx-vaadin/src/router.ts
- starters/lit-mobx-vaadin/src/styles/theme.ts
- starters/lit-mobx-vaadin/tests/pages/fetch-example/fetch-example.spec.ts
Adds the fetch example to the Lit starter.
> [Lit-Mobx-Vaadin] Fetch Example

- starters/expo-zustand-styled-components/package.json
- starters/svelte-kit-scss/src/lib/components/Counter/Counter.spec.ts
- Resolves test issues found in the `expo-zustand-styled-components` and `svelte-kit-scss` starters
> fix: resolves test issues

- starters/lit-mobx-vaadin/package.json
> add node type definitions

- starters/solidstart-tanstackquery-tailwind-modules/README.md
- starters/solidstart-tanstackquery-tailwind-modules/package.json
#1246 
This PR also has a fix for the installation command on the README.md file.
> Bump core deps version to fix current bug.

- starters/deno-oak-denodb/README.md
- starters/express-apollo-prisma/README.md
- starters/express-typeorm-postgres/README.md
- starters/serverless-framework-apollo-contentful/README.md
- starters/solidstart-tanstackquery-tailwind-modules/README.md
The command for installing some of the starter kits was broken. So I updated the README with the right commands
> Update starter command in Readme files

- starters/shopify-next-tailwind/app/compoents/Footer.tsx
- starters/shopify-next-tailwind/next.config.js
Added Netlify logo to the footer
> tdl-52: added netlify logo to the footer

- starters/shopify-next-tailwind/.env.example
- starters/shopify-next-tailwind/components/CollectionCard.tsx
- starters/shopify-next-tailwind/lib/shopify/index.ts
- starters/shopify-next-tailwind/lib/shopify/queries/policies.ts
- fixed (Warning: CollectionCard: `key` is not a prop. Trying to access it will result in `undefined` being returned.)
- Added subscription policy
> fix warning, added subscription policy

- starters/express-apollo-prisma/README.md
> docs: fix link
