packages/website/src/pages/frameworks/index.astro
Resolves #220 
The build for whatever reason expects a '.tsx' for the import path to MobileNavigation. The linter seems upset now after making this fix, but the build now functions as expected.
The change that introduced this regression can be found [here](https://github.com/thisdot/starter.dev/commit/ce393f68efcaa6e2c82085c7f8c2cc973d70397c#diff-164c9e7ead49ac55ce388ddb4647642b45501848d28538006738705f1c0eb81fL4-R4). This regression was not introduced by the merge of the new Ng-NgRx-SCSS starter as we previously thought. Also here are [the build logs](https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d2zmkukv1jdnvq/main/48) associated with the aforementioned change. It appears that this got introduced a while back but it got missed.
=> [Website] Fix Production Build by Changing MobileNavigation Import Path

starters/angular-apollo-tailwind/.gitignore, starters/angular-apollo-tailwind/package.json
Resolves #270 
Turns out storybook is using compodoc to generate the documentation section. This is super important for storybook to provide value. The docs section in the below screenshot does not render without compodoc so this is a must for storybook to run correctly.
=> [angular-apollo-tailwind] fix storybook documentation

packages/website/src/components/KitActionLinks.astro, packages/website/src/components/StickyHero.astro, packages/website/src/styles/global.css
#290 
- Made the post-scroll button positions and the pre-scroll button area to match
- Updated the links to not have underline until they are hovered, focused, or active
Loom video demonstration: https://www.loom.com/share/eb1e59eb1430442693f3b492c81adf47
=> fix: make pre-scroll / post-scroll buttons on kit details page consistent

starters/next-react-query-tailwind/.babelrc, starters/next-react-query-tailwind/.eslintrc.json, starters/next-react-query-tailwind/__mocks__/consoleMock.js, starters/next-react-query-tailwind/package.json, starters/next-react-query-tailwind/src/components/Counter/Counter.test.tsx, starters/next-react-query-tailwind/src/components/Greeting/Greeting.test.tsx, starters/next-react-query-tailwind/src/components/NavigationLink/NavigationLink.test.tsx
Added a consoleMock file to the __mocks__ folder. This is where we can control which console methods we want to mock. There is an exported function to clear all the mocks which we can run after every test. It's setup this way to try and be as DRY as possible and to be scalable across additional tests.
closes https://github.com/thisdot/starter.dev/issues/284
=> fix: mock console logs

README.md, packages/website/src/components/Contributors.astro, packages/website/src/components/HomeHero.astro, packages/website/src/components/KitActionLinks.astro, packages/website/src/components/KitHero.astro, packages/website/src/components/KitItem.astro, packages/website/src/components/KitTechnologies.astro, packages/website/src/components/NavBar.tsx, packages/website/src/components/StickyHero.astro, packages/website/src/components/TechStacksSection.astro, packages/website/src/config.tsx, packages/website/src/pages/kits-by-tool/[key].astro, packages/website/src/pages/kits-by-tool/index.astro
#291
> starter.dev is built with the community in mind. If you have ideas for improvement or new kits you'd like to see, please drop us an issue or pull request. We'd love to collaborate with you to enhance this project.
On "Frameworks", now "Kits by Tool"
Kit page
=> refactor: Update copy

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CONTRIBUTING.md
As I was stealing some of the documentation from here for our upcoming OSS repo, I noticed a couple of issues with the docs.
=> docs: fix typos and names

packages/website/src/config.tsx, starter-kits.json, starters/nuxt2-pinia-tailwind/README.md, starters/nuxt2-pinia-tailwind/nuxt.config.js, starters/nuxt2-pinia-tailwind/package.json, starters/nuxt2-pinia-tailwind/pages/index.vue
Depends on #320 
- Changed all references of `Nuxt` to `Nuxt 2`
- Updated `config.tsx` and `starter-kits.json` files
Webpage kit preview:
=> [Nuxt 2 - Pinia - Tailwind] chore: rename Nuxt kit to Nuxt 2

starter-kits.json, starters/qwik-graphql-tailwind/package.json
Note: Cannot be tested locally because in order to run `create-starter` is reading the file from  
`const STARTER_KITS_JSON_URL = 'https://raw.githubusercontent.com/thisdot/starter.dev/main/starter-kits.json';`
which is not already in place.
Fixes: #352
=> feat: Add Qwik kit to CLI

starters/qwik-graphql-tailwind/src/routes/data-fetching/data-fetching.tsx, starters/qwik-graphql-tailwind/src/routes/data-fetching/index.tsx, starters/qwik-graphql-tailwind/src/utils/useQuery.ts
Closes #346 
- Added `useQuery` that can be used to make GraphQl requests with `fetch` api.
- Refactored fetch example to use GraphQL.
- Removed some unused imports.
=> [qwik-pod] feat: use graphql queries with fetch

starters/solidjs-tanstack-tailwind/package.json
eslint needs a parser to understand modern JavaScript. Funny enough the whole Solid stack was built on top of typescript, so it needs Typescript installed to do the correct parsing.
This doesn't imply that we need TS in our own code.
=> Solidjs use parser for eslint

starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
In starter.dev we are currently showing a "welcome message" https://github.com/thisdot/starter.dev/pull/431#discussion_r1003152651, but we have to show a skeleton loading as in other kits.
=> chore: loader skeleton

README.md, packages/website/src/components/KitActionLinks.astro, packages/website/src/components/KitHero.astro, packages/website/src/components/StickyHero.astro, starters/qwik-graphql-tailwind/package.json
This PR closes #464 
"View Showcase" links were previously visible on kits that did not have a showcases. 
Links are now properly rendered based on `hasShowcase` value set in each kit's `package.json` file.
In the example picture below, `qwik-tailwind-graphql` kit does not have a showcase so the link does not display.
=> fix(#464): hide showcase links for kits with no showcase

packages/website/src/components/KitDemoHero.astro
=> chore(#463): update footer cta link for showcases

starter-kits.json, starters/angular-ngrx-scss/package.json
We noticed the Angular-NgRx kit was showing on the site but not in the CLI tool. Turns out we were missing the starter-kits command, so this fixes that.
Also turned off the showcase for now, since it's not actually complete.
=> add angular ngrx kit to cli, turn off showcase

starter-kits.json, starters/nuxt2-pinia-tailwind/package.json
- Added the key `hasShowcase` to the package.json file to indicate that the kit doesn't have a show case
- Removed duplicated vue 3 key inside sterter-kit.json file
=> [Nuxt 2 - Pinia - Tailwind] Add new field in package json

packages/create-starter/src/index.ts
When kits are generated by the user, the `hasShowcase` field also shows up in the `package.json` file. This field is needed in the starter kits but unnecessary for kits generated by the user. This PR provides a solution to exclude the unwanted field. 
Closes #476
=> fix(#476): add support for removing unwanted fields in package.json for generated kits

starters/next-routing-chakra-ui/package.json, starters/next-routing-chakra-ui/src/pages/_app.tsx, starters/next-routing-chakra-ui/src/pages/counter-example/index.tsx, starters/next-routing-chakra-ui/src/pages/fetch-example/[[...slug]].tsx, starters/next-routing-chakra-ui/src/pages/index.tsx
=> feat: adding counter example to NextJS and Chakra UI kit

starters/express-typescript-typeorm-postgres/.env.example, starters/express-typescript-typeorm-postgres/.gitignore, starters/express-typescript-typeorm-postgres/README.md, starters/express-typescript-typeorm-postgres/package.json, starters/express-typescript-typeorm-postgres/src/bootstrap-app.ts
Added express-oas-generator to generate proper swagger documentation upon serving the app
Question for reviewers: should we keep the swagger.json and swagger_v3.json files in the repository. I added them to gitignore at this time.
=> [NODE] feat: added swagger open api generator

packages/website/src/config.tsx, packages/website/src/icons/ChakraIcon.tsx, packages/website/src/icons/index.ts, starter-kits.json, starters/next12-routing-chakra-ui/package.json, starters/next12-routing-chakra-ui/src/pages/fetch-example/[[...slug]].tsx
This PR is responsible for adding the Chakra UI icon that will be displayed on the main site. 
This PR also replaces the old REST API endpoint.
=> [nextjs12-chakra ui] adding chakra ui icon

starters/svelte-kit-scss/vite.config.ts
A small change removing the alias that sveltekit was overriding anyway:
=> fix(svelte-kit-scss): remove alias causing warning from vite.config.ts

packages/website/src/layouts/KitLayout.astro, packages/website/src/styles/global.css
- Updates inline code element style on kit page contents to not include backticks
Closes #599
Before:
After:
=> fix(website): Remove backticks from inline code MD elements

starters/svelte-kit-scss/package.json, starters/svelte-kit-scss/svelte.config.js
=> [sveltekit-pod] Replace svelte-preprocess with vite-preprocess

starters/svelte-kit-scss/.storybook/preview.js
=> [svelte-kit-scss] Storybook should use the main stylesheet as the app

packages/website/src/components/Contributors.astro, packages/website/src/lib/getContributorsData.ts
- Adds fetch call to GH API to get project contributors data
- Adds footer section to collaborators card featuring contributors list
Closes #684
=> feat: Add Contributors List to Collaborate Section

starters/solidstart-tanstackquery-tailwind-modules/package.json, starters/solidstart-tanstackquery-tailwind-modules/src/components/Counter.spec.tsx, starters/solidstart-tanstackquery-tailwind-modules/src/components/Counter.tsx, starters/solidstart-tanstackquery-tailwind-modules/vite.config.ts
Each kit should have a provided a unit testing framework fully installed and configured to be used.
=> test configured, test passed

README.md
We discovered an issue where having comments included in the kit README files will break the Astro website builds. This PR just adds a comment warning about that issue.
=> chore: Warning added to README

starters/serverless-apollo-contentful/src/models/TechnologyModel.test.ts
Adds unit tests for each static method of the `TechnologyModel`
- `get`
- `getAll`
- `create`
- `update`
=> [serverless-apollo-contentful] #1046 test technology model

starters/serverless-apollo-contentful/jest.config.ts
=> [serverless-apollo-contentful] Configure test coverage report to ignore all index.ts files

starters/serverless-apollo-contentful/README.md
=> [serverless-apollo-contentful] Add deployment instructions to README

starters/express-apollo-prisma/docker-compose.yaml
Closes #916 
Modify the redis command to start the Redis server without any data persistence, all data will be lost when the server is stopped.
=> [express-apollo-prisma] caching persistence

starters/express-apollo-prisma/src/main.ts, starters/express-apollo-prisma/src/queue/job-generator-handler.ts, starters/express-apollo-prisma/src/queue/producer.ts
Closes #1085 
Adds a POST /example-job endpoint that receives a message and adds it as a job to the queue to be processed.
=> [express-apollo-prisma] Queueing: Add job generator endpoint

starters/serverless-apollo-contentful/README.md
Edit image address in README.md to make them show up in starter.dev
=> fix: README.md image addresses for starter.dev website

.gitignore, packages/create-starter/src/index.ts
* sort kits alphabetically by title
* enable autocomplete for easier searching of kits
Additionally to sorting the list I also enabled autocomplete so the user can quickly search for the kit that they are interested in:
https://user-images.githubusercontent.com/22615575/221215705-85e9e024-7d92-46bf-be01-98e343b31288.mov
=> feat: 1125 alphabetize the cli list of kits

starters/angular-ngrx-scss/README.md, starters/cra-rxjs-styled-components/README.md, starters/next12-react-query-tailwind/README.md, starters/remix-gql-tailwind/README.md
There were several broken showcase links across the different starter kits.
I fixed all of the broken showcase links.
closes #1164
=> fix: updating broken showcase links in readmes

starters/angular-ngrx-scss/package.json
Fixes #1175 
This PR drops the `zone.js` module to `0.11.4` so that `npm i` works without failing due to dependancy constraints
=> fix(angular-ngrx-scss): fix deps

starters/angular-ngrx-scss/src/app/fetch-example/fetch-example.service.ts, starters/cra-rxjs-styled-components/README.md, starters/cra-rxjs-styled-components/src/components/FetchExample/FetchExample.stories.tsx, starters/cra-rxjs-styled-components/src/components/FetchExample/FetchExample.test.tsx, starters/cra-rxjs-styled-components/src/components/FetchExample/FetchExample.tsx, starters/next12-chakra-ui/__tests__/Greeting.test.tsx, starters/next12-react-query-tailwind/src/components/Greeting/Greeting.data.tsx, starters/next12-react-query-tailwind/src/components/Greeting/Greeting.test.tsx, starters/nuxt2-pinia-tailwind/components/FetchExample/FetchExample.test.ts, starters/nuxt2-pinia-tailwind/components/FetchExample/FetchExample.vue, starters/nuxt2-pinia-tailwind/test/__mocks__/handlers/greeting.ts
I noticed this `hello` API endpoint `https://api.starter.dev/hello` is used in many of the starter kits, but that endpoint is no longer operational.
I changed them to `https://api.starter.dev/.netlify/functions/server/hello` which **_is_** operational.
**Note:** Perhaps this is not the right fix, and we should instead get the `https://api.starter.dev/hello` endpoint working again?  If so feel free to comment and close this issue.
=> fix(varied): update hello api endpoints to new working endpoint

packages/website/tsconfig.json
Just adding TS option to recognize JSX tags.
Creating this PR to `next13-zustand-bulma` since this doesn't look urgent to do in main.
=> fix: add jsx to tsconfig options

starters/next13-zustand-bulma/.storybook/preview.ts, starters/next13-zustand-bulma/.storybook/with-font-decorator.tsx, starters/next13-zustand-bulma/package.json, starters/next13-zustand-bulma/src/app/counter-example/page.tsx, starters/next13-zustand-bulma/src/app/globals.scss, starters/next13-zustand-bulma/src/components/Counter/Counter.stories.tsx, starters/next13-zustand-bulma/src/components/Counter/Counter.test.tsx, starters/next13-zustand-bulma/src/components/Counter/Counter.tsx, starters/next13-zustand-bulma/src/components/Counter/index.ts, starters/next13-zustand-bulma/src/stores/count/count.test.ts
Add a Counter Component to the `next13-zustand-bulma` starter kit
This PR NOW relies on #1177 being merged first
- added client counter component, test, and story
- put component in counter-example page
=> feat(next13-zustand-bulma): add counter component

starters/next13-zustand-bulma/.storybook/main.ts
Storybook's `Source` component has a `class="tag"` and therefore Bulma's `tag` class is being picked up.
This PR adds a hacky little fix to ignore `.tag` if it's the ancestor of a `pre` element
=> fix(next13-zustand-bulma): Bulma tag class on storybook Source component

starter-kits.json, starters/next13-zustand-bulma/package.json
This adds `next13-zustand-bulma` to the starter CLI.
Code changes according to the guide in https://github.com/thisdot/starter.dev#adding-starter-kit-to-the-cli
To test this using this branch, I followed the steps:
- In `packages/create-starter/src/index.ts`, modify the script to consider this branch instead of `main`
- [Line 11](https://github.com/thisdot/starter.dev/blob/main/packages/create-starter/src/index.ts#L11): change to `https://raw.githubusercontent.com/thisdot/starter.dev/feat/1008-add-kit-to-cli/starter-kits.json`
- [Line 74](https://github.com/thisdot/starter.dev/blob/main/packages/create-starter/src/index.ts#L74): change to `thisdot/starter.dev/starters/${options.kit}#feat/1008-add-kit-to-cli`
- Build this package and run in a separate terminal (and different directory)
=> feat(#1008): add next13-zustand-bulma kit to cli

starters/next13-zustand-bulma/.storybook/preview.ts, starters/next13-zustand-bulma/.storybook/with-body-class.tsx, starters/next13-zustand-bulma/.storybook/with-font-decorator.tsx, starters/next13-zustand-bulma/README.md
Contrary to the name of the [issue this PR resolves](https://github.com/thisdot/starter.dev/issues/1193), I've learned the [@storybook/addon-styling](https://storybook.js.org/addons/@storybook/addon-styling) addon does not provide any functionality to help with the Bulma integration, it's more about adding themes to to the storybook preview pane and being able to adapt to the themes as they are changed.
So, instead this PR takes the approach of:
-  making the `with-font-decorator` decorator a generic `withBodyClass` decorator
- updating the documentation to reflect what we are in fact doing to make Bulma and `next/font` work with  storybook
=> fix(next13-zustand-bulma): made generic withBodyClass decorator

starters/next12-chakra-ui/.vscode/launch.json, starters/next12-chakra-ui/package.json, starters/next12-chakra-ui/tsconfig.json
Hello!  This PR adds a blend of Next 12.x's Launch.json configuration (for VSCode) and the necessary `sourceMaps` entry in the `tsconfig.json`.  Finally, we add the `--inspect` option to the `npm run dev` command for convenience. While `console.log` debugging works, JS breakpoint debugging is at least old enough to vote in the United States, so I'm hoping our fellow craftspeople use it. :)
**Note: Some users online (and me) found that the "attach" works reliably _after_ the first request to a Next route that has an active breakpoint set.  Like all of life's mysteries (this, though, likely related to how TypeScript's sourcemaps are produced and consumed just-in-time) reasons for this baffling behavior may elude us until some future major, minor, or patch release elucidates its cause, or …
=> ADD: Changes needed for VSCode debug launch settings

packages/website/src/config.tsx
This PR is responsible for removing the duplicate express icon from the `config.tsx` file.
=> fix: removing duplicate express icon

starters/nuxt3-pinia-vuetify/README.md, starters/nuxt3-pinia-vuetify/package.json, starters/nuxt3-pinia-vuetify/plugins/vuetify.ts
=> [Nuxt 3 - Pinia - Vuetify] Feat: Update README 

.github/workflows/mh-deploy.yml
This PR tries to solve the broken GH action in `mh-deploy.yml`.
`workflow_dispatch` cannot be empty.
See broken action in https://github.com/thisdot/starter.dev/actions/workflows/mh-deploy.yml
=> fix: mh-deploy yml file

.github/workflows/mh-deploy.yml
Tracking the error message from `actions/setup-node`
```
Error: Some specified paths were not resolved, unable to cache dependencies.
```
https://github.com/actions/setup-node/blob/5b32c9063c6eb277dacbf3e916a8bc5d2617c5b7/src/main.ts#L64
We're setting up a cache path that doesn't exists, we should use the default path created by yarn itself.
=> fix: let setup-node find the default cache path

.github/workflows/mh-deploy.yml, packages/metrics-handler/README.md
Error in GH action
`env` needs to be declared before `run` to ensure the variables are set.
=> fix: env should be declared before the run

.github/workflows/mh-deploy.yml, packages/metrics-handler/README.md
The GH step is still broken and I didn't realize it was because of the typo on the env vars.
=> fix: use correct env vars

packages/metrics-handler/index.js
ref: https://github.com/thisdot/starter.dev/blob/main/packages/create-starter/src/metrics.ts#L13
Adjusting the body props according to `create-starter/src/metrics.js` (using `selectedKit` instead of `starterKit`).
=> fix: metrics-handler should use correct body props

starter-kits.json, starters/vue3-xstate-css/.npmrc, starters/vue3-xstate-css/README.md, starters/vue3-xstate-css/package.json, starters/vue3-xstate-css/src/components/ButtonComponent.vue, starters/vue3-xstate-css/src/main.ts
A few small cleanup tasks from an overall kit review recently.
- Simplify the README to focus more on specific decisions made
- Create a separate `dev:debug` script to run the XState visualizer in
- Set the cursor to be a pointer on the button components
- Adjusted the spelling of the kit name in the package.json description to match the other Vue3 kit
- Enforced the specific node version, to avoid conflict issues between Storybook / Node / Webpack / SSL
=> Fix: Vue3 XState cleanup issues

starter-kits.json, starters/expo-zustand-styled-components/app.json, starters/expo-zustand-styled-components/package.json
This PR fixes all incorrect kit name of `expo-zustand-styled-component` to the correct `expo-zustand-styled-components`. Now the showcase link directs users to the correct page.
=> fix: incorrect showcase link for expo kit

packages/create-starter/src/index.ts
This PR removes the strict nature for CLI kit searches and fixes a couple of small formatting inconsistencies.
=> fix: allow CLI kit searches to be more flexible

starters/angular-apollo-tailwind/README.md, starters/angular-ngrx-scss/README.md, starters/cra-rxjs-styled-components/README.md, starters/deno-oak-denodb/README.md, starters/expo-zustand-styled-components/README.md, starters/expo-zustand-styled-components/package.json, starters/express-apollo-prisma/README.md, starters/express-typeorm-postgres/README.md, starters/next12-chakra-ui/README.md, starters/next12-react-query-tailwind/README.md, starters/nuxt2-pinia-tailwind/README.md, starters/qwik-graphql-tailwind/README.md, starters/remix-gql-tailwind/README.md, starters/remix-gql-tailwind/package.json, starters/solidjs-tailwind/README.md, starters/solidstart-tanstackquery-tailwind-modules/README.md, starters/svelte-kit-scss/README.md, starters/svelte-kit-scss/package.json, starters/vue3-apollo-quasar/README.md
This goes through each starter kit and makes sure:
- No table of contents is in the README
- If a kit has a working demo, the links for the repo and live site are listed in the README and go to the right pages
- Each kit's package.json file has a `hasShowcase` value and it's set appropriately
=> Audit READMES - remove table of contents, correct demo links and hasShowcase values

.github/workflows/thank-contributor.yml
This PR is responsible for adding a github actions script that will thank contributors when they have a PR merged into this repo.
There is conditional messaging depending if they are a new contributor or returning contributor.
There is also error handling to report for invalid or expired tokens. Currently the token needs to be renewed every 90 days. 
Here are screenshots taken from a test demo I created
=> feat: adding gh action script to thank contributors

.github/workflows/send-slack-notification.yml, .github/workflows/thank-contributor.yml
This adds the GH actions script to send slack messages when a PR is merged.
=> chore: setting up GH actions slack message

.github/workflows/thank-contributor.yml
This PR accomplishes the following
Resolve Issue No.1:
The notification when a PR is merged shows up pretty quickly.
We want to delay the thank you notification by a couple of minutes.
Resolves Issue No.2:
While testing the GH action earlier, we noticed that when the curl command was run to check if a user had previously contributed, it would throw an error if the user had special characters in their username.
I added a condition to account for that so the action doesn't fail.
=> chore: adding error handling for usernames and setting delay for action

.github/workflows/ci-nuxt2-pinia-tailwind.yml, starters/nuxt2-pinia-tailwind/package.json
nuxt2-pinia-tailwind
Chrome
macOS
In a recent PR we noticed the build for this kit failed with a missing dependency issue. This should be looked into and resolved if possible. 
The build should succeed consistently.
You can find the failing build log here: https://github.com/thisdot/starter.dev/actions/runs/5357256031/jobs/9717875750
_No response_
upgraded these dependencies
- `vue`, `vue-server-renderer`, `vue-template-compiler` 
- `@nuxtjs/composition-api` because there was an error with using useContext in the setup function
and this `@nuxt/typescript-build` because of this `type` error whenever I run the app I get this error for the test files
Excessive stack depth comparing types 'Vue3Instance<{}, Readonly<ExtractPropTypes<{}>>, Readonly<ExtractPropTypes<{}>>, {}, {}, true, …
=> chore: fix build

starters/shopify-next-tailwind/README.md, starters/shopify-next-tailwind/app/compoents/ShopifyAnalytics.tsx, starters/shopify-next-tailwind/app/layout.tsx, starters/shopify-next-tailwind/lib/shopify/queries/layout.ts, starters/shopify-next-tailwind/lib/shopify/types.ts, starters/shopify-next-tailwind/package.json
=> feat: Shopify Analytics

starters/svelte-kit-scss/vite.config.ts
=> [svelte-kit-scss] Fix: exclude spec and test files
